dados = read.csv("imoveis - imoveis.csv", header=TRUE, sep=",")
attach(dados)
summary(preco)
sd(preco)
hist(preco)
summary(metragem)
sd(metragem)
summary(idade)
sd(idade)
summary(itens_embutidos)
sd(itens_embutidos)
summary(imposto_anual)
sd(imposto_anual)
plot(metragem,imposto_anual,main = "Gráfico de Dispersão", xlab = "Metragem", ylab = "Imposto Anual")
